### ISSUE TITLE
Sensor calibration

### ISSUE THREAD

**Issue by kizniche** [kizniche/Mycodo#1]

**Comment by boomstick8x** [comment]
Its a very good idea, cause my two dht22 sensors are really different. Hummidity difference ~4% and temperature ~1C, or maybe it normal?

**Comment by kizniche** [comment]
I have two sensors like this as well. This isn't high on the priority list though, so I'm not sure when I'll get a chance to research calibration methods.

**Comment by Myke974** [comment]
@boomstick8x I'll use the lower RH one for PID relay control.

**Comment by boomstick8x** [comment]
@kizniche callibration methods? Hmm, interesting...
Im thinking about taking weather alcohol or usual mercury thermometer and make some tests to find the error of each sensor.
I think calibration is just possibility to add or subtract temperature error for each sensor in Mycodo software. And for RH calibration I can use psychrometer (dont have one yet, but its easy to use two thermometers with some DIY)

@Myke974 You are using lower RH because of smaller saturate chance?

**Comment by kizniche** [comment]
The standard method is to get the environment condition to a known low and a high, so you can determine the offset at both the low and high of the measurement spectrum. This will allow a linear regression to be performed. If it's not a linear change, a more complex function will need to be calculated.

**Comment by Myke974** [comment]
![205_09_29_dht_labels01](https://cloud.githubusercontent.com/assets/1829188/10171838/267a3670-66ed-11e5-989b-e90761c3dcd1.jpg)
