### ISSUE TITLE
RaspberryPiCPUTemp needs review

### ISSUE THREAD

**Issue by etiology** [kizniche/Mycodo#144]
This is a file that has some major issues in it (codacy score of **F**) and I need some help understanding the logic behind some parts.

#### First issue - we initialize ```self._temperature``` with an ```int``` value, and later set it to ```None```, and then later a float.

init
```python 
class RaspberryPiCPUTemp(object):
    def __init__(self):
        self._temperature = 0
        self.running = True
```

later set it to ```None``` under some conditions
``` python
    def read(self):
        temperature = []
        # create average of two readings
        for _ in range(2):
            time.sleep(1)
            temperature.append(self.get_measurement())
        if (None in temperature or
                max(temperature)-min(temperature) > 10):
            self._temperature = None
            return 1
        else:
            self._temperature = sum(temperature, 0.0) / len(temperature)
            return 0
```

1. So what should we expect it to be?  An ```int```, ```None```, or ```float```?
2. Why are we checking to see if the delta is *greater than* 10?  What does it mean if it is?

**Comment by kizniche** [comment]
I once had issues with certain sensors returning incorrect data. How I solved (if you want to call it that), was to take several measurements and add them to a list (I happened to use a local temperature and a self.temperature here, so that was confusing), then take the minimum of the list and the maximum of the list, and if those values were more than 10 degrees apart, I would throw out that reading.

```python
        if (None in temperature or
                max(temperature)-min(temperature) > 10):
            self._temperature = None
            return 1
```

If they were less than 10 apart, I would take the average of the list

```python
self._temperature = sum(temperature, 0.0) / len(temperature)
```

I'm pushing a cleaned up set of classes to read the GPU and CPU temperatures in just a minute.
