### ISSUE TITLE
Add Notes/Journal entries Section

### ISSUE THREAD

**Issue by Myke974** [kizniche/Mycodo#28]
Wouldn't it be awesome to be abble to write some notes anytime to keep log of anything : 
- Grow journal
- PID settings/tuning
- personal notes and comments
Very important to have automatic time stamps affected when writing the notes/

**Comment by kizniche** [comment]
How do you think this should be implemented?

**Comment by Myke974** [comment]
I think its own tab should be a good choice good : like the data tabs, the entries could be separated into labels.
Some default labels editables by the users who got rights.

**Comment by zsole2** [comment]
I fully support this!
Since the mycodo database for storing the parameters, it is practically no way to know looking back what was changed and when, and the result of this change was relevant or not. Now we only now from the daemon log that the database was reloaded at a certain time. 
I think a journal tab (or journal button on the Data tab) would be ideal to store the PID parameters with timestamps automatically, helping for tuning the PID loop looking back days/weeks later. 
Of course text box would allow to add any personal comments, too.

**Comment by Myke974** [comment]
If we can add pictures too (I'm thinking Grow-log) !
The result would be a Web Page showing all the notes with timestamps and color to differentiate between labels and the possibility to hide/show labels.

**Comment by kizniche** [comment]
I added the relay/sensor value history logging in commit https://github.com/kizniche/Mycodo/commit/6cb09a7f47664fbb2ce5adbce53e6d8982149b20

**Comment by kizniche** [comment]
Considering how the sensor/relay change (delta) logs are set up, what do you think is the best way to implement a text logging system?

I was thinking about if all the sensor and relay change logs were combined, but they have different numbers of columns, so it would be difficult to determine what each value was. This would have worked well with the history feature, as you could see everything in relation to each other, along with text notes. But, because the columns pose a problem, the logs will have to remain separate.

Maybe a notes button on the Data tab, that will load a new page in the Data tab with an input field, a "new note" button, all notes with a timestamp, along with "edit" and "delete" buttons next to each entry. The edit button would overwrite the note with whatever is in the text box. A "new note" button will create a note from the text box and timestamp it. Delete will remove the note. What do you think?

**Comment by zsole2** [comment]
Since my system is quite stable now, I did not check the operation of the change logs... I will soon. On the other hand, I have only HT sensors in my setup, so I don't know how the columns with other sensors match or not. I can see your problem with the relay change log, though... On this topic, shouldn't a timer change log is needed for completeness?
<OFF> 
I always  wanted to add a T sensor for the ambient temperature, I have the sensor already, but reluctant to add it,  because  in that case it will be the top graph, which is in my case would be data that is nice to have, but the least important. 
So when you will not have absolutely nothing to improve, I'd suggest to find a way to reorder the sensors/graphs. I know that it is probably a lot of work, so just saying as a future feature request. 
</OFF>
...
I just run a quick test on the change log headers to see the differences... I suggest to put a title on top of the table to know which data you see currently, I got lost a few times not knowing which button was clicked last. Just repeating the button name would be enough above the header...

So I copied all headers into a spreadsheet, and apparently there are lots of similar types of columns, just their name is different based on the sensor. With the  combo sensors you can put the specific data first (hum and press) and the temp as a secondary will tail the table. Other than that, the GPIO looks different. So if you  add a 'Type' column, the whole combination looks feasible. Of course, I guess it is again a lot of coding...

As for the text boxes, I'd leave to  Myke974, as he suggested it, but your approach looks sensible.

**Comment by kizniche** [comment]
Good idea. I added a change log title above the column titles and added the timer change log in commit https://github.com/kizniche/Mycodo/commit/ff904d84d21614d22509b33edbba0741654917b9

**Comment by kizniche** [comment]
@zsole2 You can check the Log checkbox and uncheck the Graph checkbox to have the sensor be recorded but not display the graph. It will also display the data in the header when it's not graphed so you can easily see the current temperature from that sensor and still have your desired graph at the top.

**Comment by zsole2** [comment]
I know that I can turn off graphing, though I never tried it, since I have only two sensors currently, so it is not a problem scrolling a bit. 
Agree that  reordering of the graphs/sensors would be difficult, that's why said future request, if nothing else remained to work on. In any case, my idea would be to keep an ordered array of sensors, with their types, i.e. 
0 - HT
1 - T
2 - HT
3 - CO2
4 - T
and so on ...
Then rather than running separate loops for each sensor types, you would have an outside loop, enumerating the sensor-array, and based on the type of any given element, the appropriate sensor would be presented. For the graphs the same array could be used, except if the graphing is not select, it would be omitted.
As for programming it, that is way over my head...

**Comment by kizniche** [comment]
By popular demand, note-taking is included in commit https://github.com/kizniche/Mycodo/commit/79ec05f7805b8703f6a42c075f2eedc07e617d51

This is just a basic implementation with a SQLite database, so don't expect much ;)

**Comment by boomstick8x** [comment]
@kizniche would you please, when you will able to spend time for it, also add option for edit notes?

**Comment by kizniche** [comment]
That will be the next update I make to the note system. Maybe I'll get that working this weekend.

**Comment by Myke974** [comment]
WoW : that's great ! thanks !
It took me few days to show what I had in mind : please see attached picture.
![modified_cap](https://cloud.githubusercontent.com/assets/1829188/10378846/5a5d81c8-6e1c-11e5-8981-3d01a20a7228.jpg)

**Comment by kizniche** [comment]
Editable notes in https://github.com/kizniche/Mycodo/commit/a014ce6e751627ea6f52265deea270857566a0f1

**Comment by Myke974** [comment]
:+1:  AWESOME ! !

**Comment by boomstick8x** [comment]
Yeah! :+1:

**Comment by kizniche** [comment]
file uploads in https://github.com/kizniche/Mycodo/commit/a0f2e57f79bf52540bb8d0b5bcd198e3398cdb6c

**Comment by kizniche** [comment]
After much toiling with layouts and formatting, I believe I have everything with uploads working.

![mycodo 3 5 81 - fungi kylegabriel com 2015-10-10 00-22-49](https://cloud.githubusercontent.com/assets/838427/10409234/1e7b9518-6ee5-11e5-8022-78e32072a810.png)

**Comment by Myke974** [comment]
Excellent ! Thank you ! !

**Comment by kizniche** [comment]
Even though I closed this issue, feel free to comment here for any suggestions for changes/features.

**Comment by Myke974** [comment]
We need to be sure to never lose thoses notes ! with some auto-save somewhere  perhaps ?

**Comment by kizniche** [comment]
How would they get lost?

I was going to add the ability to backup at any time, so that could be what you're looking for.
