### ISSUE TITLE
Long gauge name shifts graphs' position

### ISSUE THREAD

**Issue by zsole2** [kizniche/Mycodo#390]
## Mycodo Issue Report:
  - Specific Mycodo Version: 5.5.9
 
#### Problem Description
![image](https://user-images.githubusercontent.com/11209960/35183141-7928f554-fde1-11e7-8f44-1aaa3438ad3b.png)

Both gauge's height is set at  150

### Additional Notes
The lesson: you should use short names, if you want too many gauges next to each other...

**Comment by zsole2** [comment]
Lesson 2: don't do crazy stuff:
![image](https://user-images.githubusercontent.com/11209960/35183217-88caed36-fde2-11e7-9ff5-4f1c6c9a865a.png)

**Comment by kizniche** [comment]
It's hard to determine the maximum text length because different devices will render the screen slightly differently. So, I leave it up to the user to self-regulate their text length. I try not to impose restrictions unless it's absolutely necessary and is well-defined (like cutting names on LCD lines so the data is always able to be properly displayed).

**Comment by kizniche** [comment]
I could see if I can merely create a div element that's the width of the dashboard element (minus the + icon) and try to restrict the text to that, causing a new line to form at the end.

**Comment by zsole2** [comment]
The only reason to start this issue was to leave a trail for later searches to find it (if there are people who search the issues before asking). In no way I wanted you to do more coding for a feature that any sane person could easily avoid.
