### ISSUE TITLE
Atlas pH sensor reading

### ISSUE THREAD

**Issue by alonrab** [kizniche/Mycodo#573]
Hi, will appreciate any help, many thanks!
## Mycodo Issue Report:
  -6.4.5
#### Problem Description
measure pH in i2c with atlas pH sensor
### Errors
 pH sensor is on 0x63 i2c, reading indication is working. 
pH data is not writing in log or showing in live display
tried:
add/remove data, plug/unplug and activate/deactivate

### Steps to Reproduce the issue:
can give ssh access
 
### Additional Notes
confirmed pH sensor is working by running atlas pH code in python (read, cal, slope all worked)

**Comment by kizniche** [comment]
This is a known bug that was fixed in the yet-to-be-released version 7.0. You can manually change the following line:

https://github.com/kizniche/Mycodo/blob/e7699f0cf408d77851c5d679f0a842a27337d44e/mycodo/inputs/atlas_ph.py#L70

to this:

```python
        return dict(ion_concentration=float(self._ph))
```

Save and restart the backend (Config -> Restart Backend).

**Comment by alonrab** [comment]
Thanks a bunch!
