### ISSUE TITLE
LoRaWAN Development

### ISSUE THREAD

**Issue by kizniche** [kizniche/Mycodo#598]
I'm starting this issue as a discussion thread for adding [LoRaWAN](https://lora-alliance.org/about-lorawan) support to Mycodo. I just purchased the [LoRaGo PORT – Multi-channel LoRaWAN Gateway](https://sandboxelectronics.com/?product=lorago-port-multi-channel-lorawan-gateway&attribute_rf-band=915MHz) and will be documenting my progress here.

I have had a need for remotely monitor one of my remote Mycodo systems that doesn't have internet access and rather than spend $ for a monthly cellular internet connection, LoRa seems to be a great solution. I plan to have it transmit important measurement data as well as error codes from 2.9 miles away, allowing me to be notified if an issue arises.

**Comment by Theoi-Meteoroi** [comment]
I found LoraWAN to be a rabbit hole - glad I fell into it but the implementation details are consuming, at least for me.   The topics range from RF concerns for throughput to state of the implementation of the LoraWAN spec since it is a work in progress.  Mostly stable these days from what I have built - the folks at [Sandbox](https://sandboxelectronics.com/) build good hardware that worked out of the box for me.  Mycodo is fun. LoraWAN is strenuous, for me.  But it has promise for things you didn't expect to be possible.  I'm interested.
