### ISSUE TITLE
Questions :P

### ISSUE THREAD

**Issue by itzik16** [kizniche/Mycodo#85]

**Comment by kizniche** [comment]
I don't currently have any z-wave devices, so at the moment it's just an idea. I'm not sure what you're trying to do with your CO2 sensor, but if you elaborate I may be able to help.

The I2C multiplexer helps when you have multiple sensors with the same I2C address (like the AM2315 temperature/humidity sensor). Normally, you would only be able to use only one of these sensors (because there is only one address), however, if you connect them to the multiplexer, you can read all of them. The multiplexer has a changeable address (8 addresses) and 8 channels per multiplexer, so you could theoretically have up to 64 sensors with the same I2C address in use at the same time.

The DHT22 communicates directly with the GPIO, so all you need to do is make sure you connect it to a free GPIO pin. I'm sure there are ways to expand the number of free GPIOs but I'm not that familiar with it. I doubt you'll be maxing out your free GPIO pins, so you don't really have to worry about any extra hardware to support more DHT22 sensors. Below is a diagram for connecting the DHT22.

![DHT22 Hookup to Raspberry Pi](http://www.knight-of-pi.org/wp-content/uploads/2015/03/breadboard_dht22.jpg)

**Comment by itzik16** [comment]
Thanks a lot for explaining me this mate, looking forward to see what features you will add, this script is just awesome and very useful, great job!! you are the best

**Comment by kizniche** [comment]
I may be putting Mycodo development on hold for a while. Things just got a little complicated...  https://www.reddit.com/r/motorcycles/comments/4rj1kq/stolen_ktm_690_enduro_2012_in_atlanta_ga_please/

I'll still respond to messages, but I may be preoccupied with sorting transportation out for a while. But who knows, I may end up channeling my frustration and anger into coding some kickass features.
